theme: jekyll-theme-hacker
title: Vita Troubleshooting Wiki
description: The Guide to troubleshooting your PSVita!

links:
  - name: Adrenaline Troubleshooting
    url: https://pipewarp.github.io/Vita-troubleshooting-guide/adrenaline-problems

gems:
  - jekyll-mentions
