theme: jekyll-theme-hacker
title: Vita Troubleshooting Wiki
description: The Guide to troubleshooting your PSVita!

links:
  - name: Adrenaline Troubleshooting
    url: https://google.com

gems:
  - jekyll-mentions
