theme: jekyll-theme-hacker
title: Vita Troubleshooting Wiki
description: The Guide to troubleshooting your PSVita!

links:
  - name: Home
    url: https://cimmerian-iter.github.io/Vita-troubleshooting-guide/
  - name: PSVITA Hacking Troubleshooting
    url: https://cimmerian-iter.github.io/Vita-troubleshooting-guide/hack-problems-related/
  - name: Plugin Troubleshooting
    url: https://cimmerian-iter.github.io/Vita-troubleshooting-guide/plugins-related-problem/
  - name: Adrenaline Troubleshooting
    url: https://cimmerian-iter.github.io/Vita-troubleshooting-guide/adrenaline-problems/
    

gems:
  - jekyll-mentions
